package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);

/*
*获取购物车商品信息
 */
    Cart  SelectCartByUseridAndProductid(@Param("userId") Integer userId,
                                         @Param("productId") Integer productId);

    /*
     *查询用户的购物车商品信息
     */
    List<Cart>  SelectCartByUserid(Integer userId);

  /*
  *统计用户购物信息是否全选
  * @return >0  商品没有全选
   */
  int  isCheckedAll(Integer userId);

    /*
     *删除购物车商品信息
     */
    int deleteByUserIdAndProductId(@Param("userId") Integer userId,
                                  @Param("productIdList") List<Integer> productIdList);

    /*
     *操作购物车商品是否被选中
     * @Param("check")  1:代表被选中  0：未选中
     */
    int selectOrUnselectProduct(@Param("userId") Integer userId,
                                @Param("productId")  Integer productId,
                                @Param("check") Integer check);


     /*
     *统计用户购物车中产品的数量
      */
     int get_cart_product_count(Integer userId);

    /*
     *查询用户购物车中已选中产品的数量
     */
    List<Cart> findCartListByUserIdAndChecked(Integer userId);
    /*
     *批量删除购物车中的商品
     */
int batchDelete(List<Cart> cartList);
}